### ISSUE TITLE
Build Books Data

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#1]

**Comment by duongan0711** [comment]
alo

**Comment by Nguyendo27081999** [comment]
Những ngày vừa qua chúng mình đã thảo luận trên nhóm chat ở face cũng như bàn luận trên lớp đã  chốt đề tài là làm ứng dụng đọc sách và sử dụng ngôn ngữ java. Bây giờ mọi người cùng nêu ý tưởng và các bước làm để triển khai công việc.

**Comment by Nguyendo27081999** [comment]
Những ngày vừa qua chúng ta đã thảo luận trên nhóm chat face cũng như bàn luận trên lớp đã đưa ra đề tài làm ứng dụng đọc sách sử dụng ngôn ngữ java, bây giờ mọi người cùng đưa ra ý tưởng và các bước làm để triển khai công việc.

**Comment by Nguyendo27081999** [comment]
Những ngày vừa qua chúng ta đã thảo luận trên nhóm chat face cũng như bàn luận trên lớp đã đưa ra đề tài làm ứng dụng đọc sách sử dụng ngôn ngữ java, bây giờ mọi người cùng đưa ra ý tưởng và các bước làm để triển khai công việc.

**Comment by haivt99** [comment]
Mọi người đưa ra ý tưởng về chức năng của app đọc sách xem
