### ISSUE TITLE
Lỗi truy cập chức năng 

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#10]
Xử lý các lỗi truy cập chức năng tại đây

**Comment by Nguyendo27081999** [comment]
![Uploading Screenshot_2019-12-13-14-56-52.png…]()

**Comment by Nguyendo27081999** [comment]
![Screenshot_2019-12-13-14-58-56](https://user-images.githubusercontent.com/52236865/70782302-414de280-1db9-11ea-967b-f79e76f4866f.png)

**Comment by Nguyendo27081999** [comment]
![Screenshot_2019-12-13-14-56-52](https://user-images.githubusercontent.com/52236865/70782327-562a7600-1db9-11ea-80e6-ecd8a41e6be8.png)
Khi t kích vào đây thì nó k xử lý dk

**Comment by haivt99** [comment]
(Xem lại đường dẫn từ  http://localhost/baitap1/quanlyhocsinh đi Đô, phải là http://localhost/quan-ly-hoc-sinh. Tức là các file m để sau đường dẫn của htdocs luôn chứ không tạo thư mục baitap1 nữa)[](C:\Users\Administrator\Desktop\quanlysinhvien)

**Comment by haivt99** [comment]
![quanlysinhvien](https://user-images.githubusercontent.com/52232584/70787170-b7a21300-1dc0-11ea-9f15-27e6c7718bfd.png)
Đây nhé

**Comment by Nguyendo27081999** [comment]
@haivt99  t để file sau htdoc luôn mà m. À ý là để luôn sau file htdoc à.. K phải tạo 1 thư mục nữa?

**Comment by dangbuiii** [comment]
để ở file htdoc luôn ấy @Nguyendo27081999 . Fix được chưa

**Comment by Nguyendo27081999** [comment]
Okkk.
