### ISSUE TITLE
Lỗi khi push code lên github

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#12]

**Comment by haivt99** [comment]
![loi](https://user-images.githubusercontent.com/52232584/70804480-314df700-1de9-11ea-85a7-8db42e2bf958.PNG)
T push lên toàn bị như này..

**Comment by haivt99** [comment]
@dangbuiii

**Comment by dangbuiii** [comment]
@haivt99 fix được chưa

**Comment by haivt99** [comment]
@dangbuiii  t chưa

**Comment by dangbuiii** [comment]
Thế hnao lấy máy t mà push code giao diện tiếp nhé

**Comment by Nguyendo27081999** [comment]
Okkk.. Máy dóng bị lỗi..

**Comment by Nguyendo27081999** [comment]
Okk. Máy Hảu bị lỗi

**Comment by haivt99** [comment]
T vẫn chưa fix được, lấy máy Đăng push code nha
