### ISSUE TITLE
Xử lý các chức năng của sản phẩm

### ISSUE THREAD

**Issue by Nguyendo27081999** [dangbuiii/SE03-Group13#13]

**Comment by Nguyendo27081999** [comment]
Mục đích:  Xử lý các thao tác truy cầm , xóa thêm sửa ,... của sản phẩm

**Comment by Nguyendo27081999** [comment]
@haivt99  @dangbuiii  @duongan0711  các bạn tự nhận chức năng để xử lý

**Comment by duongan0711** [comment]
Thêm sửa xoá nhéeeee

**Comment by Nguyendo27081999** [comment]
@duongan0711  okk An

**Comment by Nguyendo27081999** [comment]
@duongan0711  nhận hơi nhiều.. Nhận thêm chức năng thô.haha

**Comment by Nguyendo27081999** [comment]
T nhận chức năng add câu hỏi, giáo viên, bộ môn , lơpa học

**Comment by dangbuiii** [comment]
nhiều thế có làm được k @duongan0711

**Comment by Nguyendo27081999** [comment]
@dangbuiii  bạn nhận quản lý tạo bộ đề thi

**Comment by duongan0711** [comment]
Vì các chức năng thêm sửa xoá là gần giống nhau rồi, với trước có làm vs Nam nên vẫn đượcccc

**Comment by dangbuiii** [comment]
okkk. thế @duongan0711  nhớ tạo các issue đấy

**Comment by dangbuiii** [comment]
gặp lỗi nào cũng tạo luôn nhé

**Comment by duongan0711** [comment]
Cuối tuần off một buổi nữa nhé, cho đầy đủ, hoàn thiện trước khi thi

**Comment by dangbuiii** [comment]
vào nhóm chat video đi @duongan0711

**Comment by Nguyendo27081999** [comment]
@duongan0711  ookk An.. cuoois tuan

**Comment by haivt99** [comment]
Vào nhóm chat video đi mọi người

**Comment by haivt99** [comment]
Có thêm chức năng chat nữa ko các bạn

**Comment by duongan0711** [comment]
Các bạn đợi mình với, mình đang ngồi học ở cf nên không dám nghe 🤣🤣

**Comment by Nguyendo27081999** [comment]
@duongan0711  ok. the t tao isssue phan dang nhap, dang ki cho An de an nhan nhe

**Comment by haivt99** [comment]
@Nguyendo27081999  Bạn tạo đi, dương an đang bận

**Comment by duongan0711** [comment]
Okeeeee, iuuuu

**Comment by dangbuiii** [comment]
t nhận làm phần của giáo viên nhé
