### ISSUE TITLE
Xây dựng chức năng đăng nhập, đăng ký.

### ISSUE THREAD

**Issue by Nguyendo27081999** [dangbuiii/SE03-Group13#14]

**Comment by Nguyendo27081999** [comment]
@duongan0711   bạn sẽ nhận làm phần này nhé.. xong sớm rồi push lên

**Comment by Nguyendo27081999** [comment]
@duongan0711  cả xử lý lỗi khi đăng nhập nữa và thêm quên mật khẩu,...

**Comment by duongan0711** [comment]
Oke, về phần đăng nhập này sẽ có các chức năng: 
- Đăng kí tài khoản 
- Đăng nhập bằng tài khoản sẵn có 
- Đăng nhập bằng tài khoản facebook, google,... (nếu có thể) 
- Quên mật khẩu,

**Comment by duongan0711** [comment]
@Nguyendo27081999  @haivt99   @dangbuiii   Các bạn tôi thấy thiếu gì nữa khôngggggg

**Comment by Nguyendo27081999** [comment]
@duongan0711  cái phần liên kết facebook để mở rộng đi, hơi phức tạp..

**Comment by dangbuiii** [comment]
ứng dụng này mình làm local mà nên k dùng tk liên kết ngoài

**Comment by Nguyendo27081999** [comment]
@dangbuiii  uk. t cũng ý kiến như vậy..

**Comment by haivt99** [comment]
@duongan0711  Làm ở local c ơi, nên không liên kết được với facebook đâu

**Comment by duongan0711** [comment]
Yeppp, tớ code xong những phần còn lại rồi, phần đấy để là nếu có thể ấy, vì trước làm wordpress có phần ấy

**Comment by duongan0711** [comment]
Nhưng mà push lên đang bị lỗi ấy, @haivt99  push hộ lên vớiiiiii, t send

**Comment by Nguyendo27081999** [comment]
Okkk.. @haivt99  vậy thì hải push lên hộ An nhé

**Comment by duongan0711** [comment]
Xong chỉ mình cách fix luôn nhaaaaaa
