### ISSUE TITLE
Xây dựng chức năng của Admin

### ISSUE THREAD

**Issue by haivt99** [dangbuiii/SE03-Group13#15]
Admin gồm có các quyền quản lý sau :
+ Quản lý giáo viên
+ Quản lý lớp học
+ Quản lý học sinh
+ Quản lý môn học
+ Quản lý câu hỏi
+ Quản lý bài kiểm tra

**Comment by haivt99** [comment]
@dangbuiii  @Nguyendo27081999  @duongan0711  các bạn xem thử các chức năng thế này ổn chưa ?

**Comment by haivt99** [comment]
Có cần thêm, hay sửa gì không ?

**Comment by dangbuiii** [comment]
ổn quá rồi @haivt99

**Comment by Nguyendo27081999** [comment]
@haivt99  okk. khá ổn đấy

**Comment by duongan0711** [comment]
Thêm phần cấp quyền cho admin khác nữa
