### ISSUE TITLE
Xây dựng các chức năng của giáo viên

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#16]
Các chức năng bao gồm:
-Xem DS lớp, DS điểm
-Gửi/Xem thông báo

**Comment by Nguyendo27081999** [comment]
@dangbuiii  thêm chức năng soạn bộ đề câu hỏi cho hsinh hay ko?

**Comment by dangbuiii** [comment]
T nghĩ là không. Chức năng đó của phần admin thooi

**Comment by dangbuiii** [comment]
Chỉ nên để Admin tạo đề thôi chứ nhỉ
