### ISSUE TITLE
Xây dựng chức năng của học sinh

### ISSUE THREAD

**Issue by Nguyendo27081999** [dangbuiii/SE03-Group13#17]

**Comment by Nguyendo27081999** [comment]
Các chức năng của học sinh:
- Làm bài kiểm tra
- Xe điểm, xem danh sách thi

**Comment by Nguyendo27081999** [comment]
@dangbuiii  @haivt99  @duongan0711  có cần thêm gì nữa ko các bạn?

**Comment by dangbuiii** [comment]
có nên tạo thêm chức năng trò chuyện không ??

**Comment by Nguyendo27081999** [comment]
@dangbuiii  có.. để mn trò chuyện thảo luận vs nhau

**Comment by Nguyendo27081999** [comment]
@dangbuiii  nhưng mà có chwusc năng tắt trò chuyện khi đang thi

**Comment by Nguyendo27081999** [comment]
@dangbuiii  bổ sung thêm chức năng gì nữa ko v b?
