### ISSUE TITLE
Chọn chủ đề cho nhóm

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#3]
Thời gian dự định làm ra sản phẩm trong vòng 3 tuần - 1 tháng. Mọi người cân nhắc đề đưa ra chủ đề cho hợp lý

**Comment by dangbuiii** [comment]
Theo mình nên làm một chủ đề về học tập

**Comment by duongan0711** [comment]
Nhất trí, nhưng chủ đề học tập rộng đó,

**Comment by dangbuiii** [comment]
Mình sẽ viết bằng Python nhỉ.. còn về dữ liệu sẽ làm trên MySQL

**Comment by duongan0711** [comment]
Quản lý thông tin sinh viên, học sinh hay điểm số,tình trạng sức khoẻ  nhỉ? 
Chắc chắn có database rồi, ngôn ngữ thì python cho dễ 🤣

**Comment by dangbuiii** [comment]
Theo mình sẽ làm : 
- Web để sinh viên có thể thi trắc nghiệm trên đó
- có 2 tài khoản là : Giáo viên(admin) và Sinh Viên

**Comment by haivt99** [comment]
Giáo viên : Có thể up đề thi, chấm điểm cho từng học sinh tham gia vào khóa học ( lớp học ) của mình

**Comment by haivt99** [comment]
Mà mình tạo ngân hàng câu hỏi đề thi trước, giáo viên có thể tạo thêm câu hỏi luôn nhá

**Comment by dangbuiii** [comment]
okkk

**Comment by haivt99** [comment]
Vậy chọn ngôn ngữ Python để dùng flask rồi deloy trên web nhé
