### ISSUE TITLE
Các chức năng chính của sản phẩm

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#4]
Bàn luận để đưa ra các chức năng của sản phẩm

**Comment by Nguyendo27081999** [comment]
Các b đưa ra chức năng đi để triển khai... Mn đưa ra xong đó cùng chốt lại và làm

**Comment by dangbuiii** [comment]
Giáo viên : 
+ có tài khoản riêng truy cập
+ Nhận xét bài học viên
+ Tạo, phân chia lớp học

**Comment by haivt99** [comment]
Nếu có thể thì thêm 
Giáo viên : 
- Thêm được đề thi 
- Xem được điểm của các học viên trong lớp
Các bạn thấy thế nào

**Comment by haivt99** [comment]
Học viên : 
- Có tài khoảng riêng truy cập
- Tham gia lớp học
- Làm bài thi và biết kết quả sau khi kiểm tra

**Comment by Nguyendo27081999** [comment]
Thế chúng mình làm câu hỏi vấn đề gì mn?
KHXH hay tất cả các vđ xung quanh

**Comment by haivt99** [comment]
@Nguyendo27081999  Câu hỏi liên quan đến các môn học khoa học tự nhiên hoặc khoa học xã hội hoặc câu hỏi tổng hợp liên quan tới nội dung thi THPT Quốc Gia được ko?

**Comment by dangbuiii** [comment]
okk. bây h minh bắt đầu làm chứ nhỉ.. chắc bước đầu tạo database

**Comment by Nguyendo27081999** [comment]
Mà t nghe trên lớp a ý bảo có phần gù mà k cần tạo db. Nó tự tạo sẵn cho mk r

**Comment by haivt99** [comment]
Vẫn tạo database bằng câu lệnh query bình thường chứ, trên lớp là anh Nguyên bảo framework hỗ trợ thôi

**Comment by dangbuiii** [comment]
ukk mình tạo database như bình thường. Mình làm 1 cái class diagram cho dễ hình dung nhỉ

**Comment by haivt99** [comment]
@dangbuiii  ok t thấy ổn đấy, lên trang creately tạo class diagram cho dễ hình dung bài toán hơn

**Comment by dangbuiii** [comment]
okkk @haivt99

**Comment by Nguyendo27081999** [comment]
@dangbuiii  @haivt99  @duongan0711  nên thêm chức năng tạo admin để quản lý các câu hỏi và thí sinh

**Comment by dangbuiii** [comment]
Update: 
GV : Thêm các chức năng
 + Thêm ,sửa, xóa các câu hỏi

**Comment by Nguyendo27081999** [comment]
@dangbuiii  uk.. ngoài ra t nghĩ giáo viên có thể quản lý quan sát học sinh nếu có vi phạm quy chế thì có nút cảnh báo

**Comment by haivt99** [comment]
À thêm cả lấy cookie được không, ví dụ học sinh đang thi mà bị out ra vì 1 lí do gì đó thì vẫn có thể tiếp tục thi tiếp mà không bị mất dữ liệu trước đó

**Comment by Nguyendo27081999** [comment]
@haivt99 uk ý tưởng cx hay đó..

**Comment by dangbuiii** [comment]
Có thể thêm bảng xếp hạng kết quả thi của các sinh viên không nhỉ??

**Comment by Nguyendo27081999** [comment]
@dangbuiii  ý tưởng đó cx hay đó nhưng nếu ko làm được thì có thể để mở rộng cũng được.

**Comment by haivt99** [comment]
@dangbuiii  theo t nghĩ thì còn 2 tuần thôi mà nhiều chức năng chưa xử lý được nên từ từ nhé, nếu thừa thời gian thì cả nhóm làm tiếp nha

**Comment by Nguyendo27081999** [comment]
@haivt99  t cx nghĩ như vậy

**Comment by haivt99** [comment]
Mọi người ơi, thêm chức năng chat nhóm giữa các bạn học sinh được ko ? @dangbuiii  @Nguyendo27081999  @duongan0711

**Comment by Nguyendo27081999** [comment]
@dangbuiii  @Nguyendo27081999  @haivt99  @duongan0711  có nên thên chứ  năng như sai mật khẩu sẽ cấp lại đk ko?

**Comment by duongan0711** [comment]
Cái này chắc chắn phải có đấy

**Comment by Nguyendo27081999** [comment]
Thế còn thêm chức năng gì nữa @duongan0711
