### ISSUE TITLE
Tạo Database

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#5]

**Comment by dangbuiii** [comment]
Phân tích bài toán, t thấy class Giáo viên sẽ như sau:
-Attributes:
+TeacherID
+TeacherName
Methods:
+CreateNewTest()
+EvaluateTest()
+CommentTest

**Comment by dangbuiii** [comment]
Sinh viên:
-Attributes:
+StudentID
+StudentName
Methods:
+SubmitTest()
+CommentTest()

**Comment by dangbuiii** [comment]
Mọi người bổ sung thêm

**Comment by Nguyendo27081999** [comment]
À thế có cho thêm thông tin Sv ko. Ví dụ kích vào thì biết được lớp nào này năm sinh chẳng hạn

**Comment by Nguyendo27081999** [comment]
Còn thêm data gì nuaz ko

**Comment by Nguyendo27081999** [comment]
T nghĩ mình còn phải cho thêm levels, tối tượng, chủ đề nữa

**Comment by dangbuiii** [comment]
Update: 
Table Admins gồm :
- admin_id: int
- username: varchar
- email:varchar
- password:varchar
- name: varchar
- avatar:varchar
- birthday:date

**Comment by dangbuiii** [comment]
Table Classes:
- class_id: int
- grade_id:int
- class_name:varchar
- teacher_id:int

**Comment by Nguyendo27081999** [comment]
T bổ sung thêm:
Table teacher: 
- teacher id
- username
- email
- pass
- name
- last_login
- gender
- avatar
- birthday

**Comment by Nguyendo27081999** [comment]
Table student:
- student_id
- username
- email
- class_id
- gender
- avatar
- birthday
- doing_exam
- starting_time
- time_remainting

**Comment by dangbuiii** [comment]
Table Test:
- test_code: int
- test_name: varchar
- subject_id: int
- grade_id: int
- total_questions: int
- time_to_do: int
- status_id: int
- timest: timestamp

**Comment by Nguyendo27081999** [comment]
Nói chung phần DATA chức năng cĩng khá đầy đủ r.. Có gì ae bổ sung thêm. Bh ae chỉnh lại để push lên

**Comment by dangbuiii** [comment]
okk @Nguyendo27081999 để thêm 1 vài class phụ nữa

**Comment by dangbuiii** [comment]
rồi push lên nhé

**Comment by dangbuiii** [comment]
à nên tạo một class diagram trên https://app.creately.com/diagram/create cho ae dễ hình dung

**Comment by Nguyendo27081999** [comment]
Bây h push code database đi

**Comment by dangbuiii** [comment]
[https://drive.google.com/file/d/1bZHHzZfX85saSn5tb-oYq7aAdmokcwH0/view?usp=sharing](url)

**Comment by dangbuiii** [comment]
![Untitled Document](https://user-images.githubusercontent.com/45058569/69964173-7306b400-1544-11ea-8c7a-6a2fc0f33295.jpg)

**Comment by dangbuiii** [comment]
mọi người chỉnh sửa nhé

**Comment by Nguyendo27081999** [comment]
Okkk để t xem qua

**Comment by Nguyendo27081999** [comment]
Okk để t xem qua

**Comment by duongan0711** [comment]
Okeee

**Comment by dangbuiii** [comment]
t push code lên rồi nhé

**Comment by duongan0711** [comment]
T thấy rồi

**Comment by haivt99** [comment]
Mình thấy rồi nhá, push lên branch database nhìn cho dễ, cơ ai push code phần chức năng thì checkout sang branch nhé

**Comment by haivt99** [comment]
Gửi database lên github đi @Nguyendo27081999

**Comment by haivt99** [comment]
Database mới thêm data về Giáo viên, học sinh, môn học và các câu hỏi nhé

**Comment by Nguyendo27081999** [comment]
Okk.. Đang thêm nốt r.. Lát gửi nha.

**Comment by haivt99** [comment]
@Nguyendo27081999  gửi lên đi Đô để còn sửa chứ

**Comment by Nguyendo27081999** [comment]
Mn ơi. Tạo sao của t khi kích vào 1 chức năng trên giao diện lại bị lỗi v?

**Comment by duongan0711** [comment]
Bị lỗigif v

**Comment by duongan0711** [comment]
Cap lại màn hình xem nào

**Comment by Nguyendo27081999** [comment]
À nó ghi ko thể xử lý yêu cầu này

**Comment by Nguyendo27081999** [comment]
Okk. Đợi  tý

**Comment by Nguyendo27081999** [comment]
![15762140355135515466001357152510](https://user-images.githubusercontent.com/52236865/70770967-14da9c00-1da2-11ea-9015-6d7d08fe4139.jpg)

**Comment by Nguyendo27081999** [comment]
@haivt99  @duongan0711  @dangbuiii  cái kia là lỗi gì v?

**Comment by Nguyendo27081999** [comment]
@haivt99  @dangbuiii   có pit lỗi gì ko b

**Comment by dangbuiii** [comment]
Có. Tạo issue mới để fix lỗi nhé

**Comment by dangbuiii** [comment]
@Nguyendo27081999 vào issue mới tạo để cmt lỗi nhé

**Comment by dangbuiii** [comment]
Cmt cả ảnh để xem nhé

**Comment by Nguyendo27081999** [comment]
Okkk... Để t gửi ảnh cho

**Comment by Nguyendo27081999** [comment]
Các bạn tranh thủ nộp câu hỏi để t hoàn thành

**Comment by Nguyendo27081999** [comment]
Database đã hoàn thành.. Done...
