### ISSUE TITLE
Thu thập các câu hỏi kỳ thi THPT Quốc Gia (data)

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#6]

**Comment by Nguyendo27081999** [comment]
Câu hỏi liên quan đến Sử Địa Văn và các vấn đề KHXH.. các bạn gửi link các câu hỏi để mn tham khảo á

**Comment by dangbuiii** [comment]
Địa lý: https://vietjack.com/bai-tap-trac-nghiem-dia-li-12/

**Comment by haivt99** [comment]
Câu hỏi và đáp án đề thi lịch sử này : https://vietjack.com/bai-tap-trac-nghiem-lich-su-12/
Tham khảo để cho luôn vào database nhé

**Comment by Nguyendo27081999** [comment]
Okkkk..

**Comment by dangbuiii** [comment]
Lich su : https://vietjack.com/bai-tap-trac-nghiem-lich-su-12/

**Comment by haivt99** [comment]
Mình làm xong database rồi, push lên luôn nhé

**Comment by dangbuiii** [comment]
ơ sao lại cmt vào đây @haivt99

**Comment by Nguyendo27081999** [comment]
Push dàn database lên đi.. Phần data cx gần ok r

**Comment by Nguyendo27081999** [comment]
@duongan0711  tìm câu hỏi trắc nghiệm về môn lịch sử xong gyiwr cho t?

**Comment by duongan0711** [comment]
Oke, 8h tối nay nhé

**Comment by Nguyendo27081999** [comment]
@dangbuiii  tìm giúp t về môn Địa lý

**Comment by Nguyendo27081999** [comment]
@haivt99  tìm giúp t về môn văn học

**Comment by Nguyendo27081999** [comment]
Còn 1 số môn t sẽ tìm nốt... Tối nay các bạn gửi ở đây nhá.. Xong t hoàn thiện

**Comment by duongan0711** [comment]
Khoảng bao nhiêu đề nhỉ? Mỗi khối chục đề nhé 🤣

**Comment by Nguyendo27081999** [comment]
@duongan0711 okk. Nhưng ít thôi cx đuoẹc. Tại còn nhiều môn mà

**Comment by Nguyendo27081999** [comment]
@duongan0711  có gì lúc demo lên xong mình thêm câu hỏi cũng được

**Comment by Nguyendo27081999** [comment]
@duongan0711  còn nhiều khối nữa

**Comment by Nguyendo27081999** [comment]
@dangbuiii  @haivt99  gửi câu hỏi lên đây đi..

**Comment by Nguyendo27081999** [comment]
@dangbuiii  push câu hỏi lên đi b

**Comment by dangbuiii** [comment]
okk để mở máy đã
