### ISSUE TITLE
Thiết kế giao diện

### ISSUE THREAD

**Issue by Nguyendo27081999** [dangbuiii/SE03-Group13#8]

**Comment by haivt99** [comment]
![giaodien](https://user-images.githubusercontent.com/52232584/69228692-9762a800-0bb6-11ea-8211-ae4a806b942c.png)
@Nguyendo27081999  @Nguyendo27081999  @duongan0711  mọi người xem home page ổn chưa ? cho t ý kiến để design lại.

**Comment by Nguyendo27081999** [comment]
giao diện khá ổn rồi đấy.

**Comment by duongan0711** [comment]
Okkkkk

**Comment by Nguyendo27081999** [comment]
@duongan0711 okkk an...

**Comment by duongan0711** [comment]
Ngoài ra, có nên thêm background cho đẹp không nhỉ

**Comment by Nguyendo27081999** [comment]
uk. thế cũng đưojc @duongan0711

**Comment by Nguyendo27081999** [comment]
Các b xem lại giao diện để chốt lại nào..

**Comment by dangbuiii** [comment]
avatar user nen lay cai nao moi nguoi

**Comment by haivt99** [comment]
Lấy ảnh đơn giản thôi bạn, nhìn diu dịu mắt là được @dangbuiii

**Comment by dangbuiii** [comment]
![79158992_940538426329180_8605956134274072576_n](https://user-images.githubusercontent.com/45058569/70719500-b3281c80-1d24-11ea-8af1-5855b87e1c9b.png)
Giao diện phần Login sẽ như thế này nhé mn

**Comment by dangbuiii** [comment]
Bây h t push code phần giao diện Login lên nhé

**Comment by haivt99** [comment]
@dangbuiii  ok push lên luôn nhánh master đi bạn

**Comment by Nguyendo27081999** [comment]
@dangbuiii  sao chưa push đk à

**Comment by dangbuiii** [comment]
Đang bị lỗi... Đang fix nhé

**Comment by dangbuiii** [comment]
đang tiếp tục push code giao diện nhé. được 1 nửa rồi

**Comment by duongan0711** [comment]
Cần hỗ trợ gì thêm honggg

**Comment by Nguyendo27081999** [comment]
Thay giao diện ảnhbạn gái đi... Thi lại để ảnh ý hơi kì...

**Comment by haivt99** [comment]
Chỉ là ảnh đại diện thôi mà, tại set default ấy

Vào BE 2562 thg 12 18, Th 4 lúc 11:14 Nguyendo27081999 <
notifications@github.com> đã viết:

**Comment by Nguyendo27081999** [comment]
Yepp.. Thế giao diện cogn chỉnh đối gì nữa ko v

**Comment by duongan0711** [comment]
Cũng ổn ổn rồi đấy

**Comment by haivt99** [comment]
Mai @dangbui mang lap mượn để push code nhé

Vào BE 2562 thg 12 18, Th 4 lúc 11:44 duongan0711 <notifications@github.com>
đã viết:

**Comment by Nguyendo27081999** [comment]
@haivt99 @dangbuiii  2 bạn push nốt code phần tạo giao diện đi cho xong..

**Comment by haivt99** [comment]
Các bạn muốn code tiếp ko :))

Vào Th 5, 9 thg 1, 2020 lúc 15:08 Nguyendo27081999 <notifications@github.com>
đã viết:

**Comment by dangbuiii** [comment]
cmt nhiều vd, mà thầy cho điểm k được cao lắm, buồn ghê các b ơi
