### ISSUE TITLE
Lỗi khi push code lên github

### ISSUE THREAD

**Issue by dangbuiii** [dangbuiii/SE03-Group13#9]
Các bạn thảo luận để fix lỗi qua issue này nhé

**Comment by Nguyendo27081999** [comment]
@dangbuiii  @haivt99  pussh giao diện thì bị lỗi gì à?

**Comment by haivt99** [comment]
Đã fix được lỗi khi push code rồi nhé mọi người ^^

**Comment by Nguyendo27081999** [comment]
Okkk b

**Comment by dangbuiii** [comment]
Okk @haivt99

**Comment by dangbuiii** [comment]
Lỗi ở đâu vậy

**Comment by Nguyendo27081999** [comment]
@haivt99  thấy máy hải bị lỗi
